name = "AdventOfCode2020"
uuid = "82779f9d-6177-4b61-aadc-1750be0a5a53"
version = "0.1.0"
authors = ["jambolo"]

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.13.1"
julia = "1.12"
